// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9wipLdkTEeIH_V_iokq_E3rrK9TsMjBY',
    appId: '1:566421081596:web:9c0230e35f2a11d3697679',
    messagingSenderId: '566421081596',
    projectId: 'green2-ac285',
    authDomain: 'green2-ac285.firebaseapp.com',
    databaseURL: 'https://green2-ac285-default-rtdb.firebaseio.com',
    storageBucket: 'green2-ac285.appspot.com',
    measurementId: 'G-ETPMQ9T9MM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcGYWCxJYCqDIXXWMIJU1BonrhgcY0ty0',
    appId: '1:566421081596:android:0a99253ba80b8b36697679',
    messagingSenderId: '566421081596',
    projectId: 'green2-ac285',
    databaseURL: 'https://green2-ac285-default-rtdb.firebaseio.com',
    storageBucket: 'green2-ac285.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUrvB52T9MigHlzMjThdSUUNZMfQpe9p0',
    appId: '1:566421081596:ios:e1fe675fd7153838697679',
    messagingSenderId: '566421081596',
    projectId: 'green2-ac285',
    databaseURL: 'https://green2-ac285-default-rtdb.firebaseio.com',
    storageBucket: 'green2-ac285.appspot.com',
    iosBundleId: 'com.example.green2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUrvB52T9MigHlzMjThdSUUNZMfQpe9p0',
    appId: '1:566421081596:ios:f800c311d8490da8697679',
    messagingSenderId: '566421081596',
    projectId: 'green2-ac285',
    databaseURL: 'https://green2-ac285-default-rtdb.firebaseio.com',
    storageBucket: 'green2-ac285.appspot.com',
    iosBundleId: 'com.example.green2.RunnerTests',
  );
}
